#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Uncertainty Modelling for Engineers
logo                        : FORM.png
author                      :
copyright                   : "2020"  # Copyright year to be placed in the footer
repository:
  url: https://github.com/uncertainty-for-engineers/uncertainty-modelling-for-engineers
  path_to_book: uncertainty-book  # Optional path to your book, relative to the repository root
  branch: main
html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
latex:
  latex_engine: xelatex
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    latex_toplevel_sectioning: 'part'
launch_buttons:
  colab_url: "https://colab.research.google.com"
